FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Feature branch level 1

Polls is a simple API allowing consumers to view polls and vote in them.

## Is this top Collection [/level]

### List All Tops [GET]

+ Response 200 (application/json)

        {"level":1}